version: "3"
services:
  web:
    build:
      # `context` should be a path to a directory containing a Dockerfile
      context: ./fastapi_app # ./flask_app #
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
