[tool.poetry]
name = "oedatamodel_api"
version = "0.1.0"
description = "API to connect OEP with MODEX frameworks"
authors = ["Hendrik Huyskens <hendrik.huyskens@rl-institut.de>"]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.61.1"
jinja2 = "^2.11.2"
uvicorn = "^0.12.0"

[tool.poetry.dev-dependencies]
flakehell = "^0.6.1"
pytest = "^6.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
